### ISSUE TITLE
New Model Request: U-Net

### ISSUE THREAD

**Issue by wkeithvan** [keras-team/keras-applications#10]
Is it possible to add a U-Net architecture to this list (https://arxiv.org/abs/1505.04597)? This is very popular in current medical imaging research and would be very helpful to have an officially supported version of the model that is pretrained on medical images. Even an untrained, but official version of the model would be a great starting spot for the medical research community.

There is an official version of the model with weights maintained by the authors, however, it uses Caffe (https://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/). A Keras version would be helpful as many in the medical research industry are already using Keras/TensorFlow.

**Comment by taehoonlee** [comment]
@wkeithvan, Thank you for your suggestion. There are plans to add UNet, and currently you can refer to [this repo](https://github.com/zhixuhao/unet).

**Comment by wkeithvan** [comment]
Thanks... already using that repo. Looking forward to seeing an official U-Net in the future!

**Comment by taehoonlee** [comment]
The #24 will address this issue.
