### ISSUE TITLE
Self-train These Models on ImageNet

### ISSUE THREAD

**Issue by fzyzcjy** [keras-team/keras-applications#103]
Hi! Thank you very much for these wonderful libraries!
I want to have a `mobilenet` with `alpha=0.125` (or possibly smaller) to make it even more light-weight. Since there is no pretrained models (only with alpha=0.25 and so on), I want to *first pretrain it on mobilenet, and then use it for fine-tuning*. Therefore, I would appreciate it if *I could be given the code you use to pretrain it on mobilenet*. Thank you very much!

**Comment by taehoonlee** [comment]
@fzyzcjy,

The keras-applications is designed for inference only, so don't provide training details such as data augmentation (e.g., rotating, shifting), optimization hyperparameters (e.g., lr, decay), and a release number of ImageNet used for training.

For such information, you can check the original repositories shown in the table in README.

**Comment by fzyzcjy** [comment]
Thank you very much!

**Comment by fzyzcjy** [comment]
@taehoonlee Sorry for bothering again. So I just ask the training details on corresponding TensorFlow GitHub. However, could you please give the conversion from TF to Keras? Thank you very much for your reply!

**Comment by taehoonlee** [comment]
@fzyzcjy, The conversions have been done by contributors. They must have the conversion script.

**Comment by fzyzcjy** [comment]
@taehoonlee Thanks very much! How can I contact them?

**Comment by taehoonlee** [comment]
@fzyzcjy, You can find individual authors on [the keras commit logs](https://github.com/keras-team/keras/commits).

**Comment by fzyzcjy** [comment]
@taehoonlee Thanks! (sorry i forgot to reply 2 months ago when seeing your message)
