### ISSUE TITLE
Parameter 'depth_multiplier' has been deprecated in MobileNetV2 API, docs don't mention this

### ISSUE THREAD

**Issue by SJCaldwell** [keras-team/keras-applications#108]
I was having some trouble wherein attempting to use the MobileNetV2 API as is shown in the documentation https://keras.io/applications/#mobilenetv2 resulted in the following error.

```
keras.applications.mobilenet_v2.MobileNetV2(input_shape=None, alpha=1.0, depth_multiplier=1, include_top=False, weights='imagenet', input_tensor=None, pooling=None)
```

After reading through github and finding #63 , I discovered depth_multiplier was deprecated in mobilenetv2. It would help if this deprecation was clear in the docs!

**Comment by taehoonlee** [comment]
@SJCaldwell, Thank you for being patient. It has already been reflected in keras-team/keras#12328. But just uploading autogen docs was not done recently. It can only be done by Chollet.

**Comment by taehoonlee** [comment]
Closed as the docs have been updated recently.
