### ISSUE TITLE
Mobilenet V2 error message wrong

### ISSUE THREAD

**Issue by aguang1201** [keras-team/keras-applications#11]
keras ver:2.2.0
When use Mobilenet V2, alpha is wrong(example:0.25).The error message is as following:
ValueError: If imagenet weights are being loaded, alpha can be one of`0.25`, `0.50`, `0.75` or `1.0` only.
But the right alpha is:0.35, 0.50, 0.75, 1.0, 1.3, 1.4.
Please check the mobilenet_v2.py 310th row.

**Comment by taehoonlee** [comment]
Thank you for the comment, @aguang1201. It will be updated.

**Comment by taehoonlee** [comment]
Please refer to [the commit](https://github.com/keras-team/keras-applications/commit/f7bc2d2a6b3f7c272df381bd7589bbbf5c6aa4c9).
