### ISSUE TITLE
Reshape error when making ResNext model with input shape (None, None, 3).

### ISSUE THREAD

**Issue by YuanYunshuang** [keras-team/keras-applications#110]
I want to input images with different size. And the input shape is set to (None, None, 3).
But the error occurs at line 229 and 230 of "resnet_common.py"

`x_shape = backend.int_shape(x)[1:-1]`
`x = layers.Reshape(x_shape + (groups, c, c))(x)`
The first line returns a shape with None, but the reshape function raised the error "None values not supported"
How can I solve this issue?

**Comment by taehoonlee** [comment]
@YuanYunshuang, the issue will be resolved by #85. I'll close the issue for now. Please feel free to open it again at any time if you have additional comments.
