### ISSUE TITLE
Difficulty in finding the name of category and respective probabilities of an image

### ISSUE THREAD

**Issue by csitaula** [keras-team/keras-applications#112]
Hi,
I am working on probability features for my research. I am trying to extract the label and probability for all 1000 category for the input image. How to do that? decode_predictions only returns the top probabilities. I don't need top probabilities. Just list of categories in a natural way. HOw to solve my problem? Thanks

**Comment by taehoonlee** [comment]
@csitaula, You can load information of all the 1000 classes as follows:
```python
import json
with open('~/.keras/models/imagenet_class_index.json') as f:
    classes = json.load(f)
```
