### ISSUE TITLE
Loading pretrained weights fails when `input_tensor` is non-trivial

### ISSUE THREAD

**Issue by mahehu** [keras-team/keras-applications#120]
[Documentation](https://keras.io/applications/#build-inceptionv3-over-a-custom-input-tensor) gives this example for initializing the pretrained network with custom `input_tensor`:
```
input_tensor = Input(shape=(224, 224, 3)) 
model = InceptionV3(input_tensor=input_tensor, weights='imagenet', include_top=True)
```
However, adding another layer at the input fails:
```
input_tensor = Input(shape = (224,224,3))
input_tensor = Conv2D(3, kernel_size = (1,1))(input_tensor) # new layer
model = InceptionV3(input_tensor=input_tensor, weights='imagenet', include_top=True)
```
This results in the following error:
```
ValueError: You are trying to load a weight file containing 189 layers into a model with 190 layers.
```
With `weights=None` or without the `Conv2D` layer this works fine. 

I'm using keras version 2.2.4 and keras-applications version 1.0.8.

**Comment by taehoonlee** [comment]
@mahehu, I hope the following workaround will help you.
```python
from keras.models import Model
from keras.layers import Input, Conv2D

newinput = Input(shape=(224,224,3))
conv = Conv2D(3, kernel_size=1)(newinput)
newmodel = Model(inputs=[newinput], outputs=[model(conv)])
```

**Comment by taehoonlee** [comment]
@mahehu, I'll close the issue for now. Please feel free to open it again at any time if you have additional comments.

**Comment by mahehu** [comment]
Thanks, this solved the issue. Sorry for not remembering to comment on that.

Thanks for your great work!
