### ISSUE TITLE
For what reason I need to use a specific input shape when loading imagenet weights, even though any shape works fine when transferring?

### ISSUE THREAD

**Issue by DableUTeeF** [keras-team/keras-applications#122]
I just want to train MobileNet with larger images but I have to put an Input tensor to the function otherwise it will stuck in this line.

https://github.com/keras-team/keras-applications/blob/master/keras_applications/imagenet_utils.py#L292

I believe this line is really unneeded.

Is this against the rule or should I use Pull request instead?

**Comment by taehoonlee** [comment]
@DableUTeeF, You must designate the input_shape as `(rows, cols, channels)`, thus the line is necessary.

**Comment by DableUTeeF** [comment]
Why is it necessary?
Of cource you need to specific the shape but it's not has to be (224, 224,
3) right?
Even (416, 416, 3) works just fine but that line make this errer!!

**Comment by taehoonlee** [comment]
@DableUTeeF, the following example works fine without an error.
```python
import numpy as np
from keras.applications.mobilenet import MobileNet
model = MobileNet(include_top=False, input_shape=(416, 416, 3))
print(model.predict(np.random.random((1, 416, 416, 3))).shape)
model2 = MobileNet(weights=None, input_shape=(416, 416, 3))
print(model2.predict(np.random.random((1, 416, 416, 3))).shape)
```

**Comment by DableUTeeF** [comment]
Indeed
But for some reasons this raise error in Colab.
```

model = tf.keras.applications.nasnet.NASNetLarge(
      include_top=False,
      weights='imagenet',
      input_tensor=None,
      input_shape=(224, 224, 3),
      pooling=None)


```

**Comment by DableUTeeF** [comment]
Well, I tried it again and the MoblieNet works.
But NasNet raise this
```
/usr/local/lib/python3.6/dist-packages/keras_applications/imagenet_utils.py in _obtain_input_shape(input_shape, default_size, min_size, data_format, require_flatten, weights)
    290                                  'and loading `imagenet` weights, '
    291                                  '`input_shape` should be ' +
--> 292                                  str(default_shape) + '.')
    293         return default_shape
    294     if input_shape:

ValueError: When setting `include_top=True` and loading `imagenet` weights, `input_shape` should be (331, 331, 3).
```

**Comment by taehoonlee** [comment]
@DableUTeeF, the `ValueError` of NASNet is mandatory in order to reproduce the original results. If you want to train from scratch, you can put `weights=None` as an argument.

**Comment by DableUTeeF** [comment]
Of cource not!!
I don't mean to train it from scratch so that's why I put the
`weights='imagenet'` no?
The results are far better when transferring even if you change the size,
that's why I've said this should not raise error.

**Comment by DableUTeeF** [comment]
Well, suppose the MobileNet does work but the NASNet doesn't, it might be
something from the NASNet code rather than the utils.

**Comment by taehoonlee** [comment]
@DableUTeeF,

1. When `include_top=True`, both the following models must raise ValueError.
```python
MobileNet(input_shape=(416, 416, 3))
NASNetLarge(input_shape=(416, 416, 3))
```

2. When `include_top=False`, only the NASNet must raise ValueError. It is intended behavior because [this line](https://github.com/keras-team/keras-applications/blob/master/keras_applications/nasnet.py#L513) causes structural changes. In other words, the NASNet with `include_top=any, input_shape=(None, None, 3)` may differ from the intended structure of the authors.
```python
NASNetLarge(include_top=False, input_shape=(416, 416, 3))
```

**Comment by DableUTeeF** [comment]
I know that!!
Please look at my answer above again (I don't have a PC around), I clearly
specific `include_top=False` in the `NASNetLarge()`.
That's should means the Nasnet code sends a `True` param even though I put
it `False`.

**Comment by taehoonlee** [comment]
@DableUTeeF, the ValueError is intended. And the error message can be misleading. Do you want to revise the error message?

**Comment by DableUTeeF** [comment]
It's not about the message.
I mean, it's raise error when it should not.
 1.) I put a specific `include_top=False` but the error said `include_top`
is True, this is a bug right?. And if `include_top` is False then whatever
input size I use shouldn't be any problem right? In fact, this does work in
MobileNet. Well, my question at first misleading this. But this same params
raise Valueerror when I change it to NasNetLarge.
 2.) Despite the 1.) error, if I change the weights to None and then
manually load the weight in .keras, it works!! Which means this is
difinitely a bug in NasNet code.

**Comment by DableUTeeF** [comment]
The main problem now is "Why it's only error when I use NASNet.

**Comment by taehoonlee** [comment]
@DableUTeeF, That is not a bug. It is intended behavior because [this line](https://github.com/keras-team/keras-applications/blob/master/keras_applications/nasnet.py#L513) causes structural changes. In other words, the NASNet with `include_top=any, input_shape=(None, None, 3)` may differ from the intended structure of the authors.

**Comment by DableUTeeF** [comment]
@taehoonlee As I said, I can just create model with `weight=None` and load the "official Imagenet weights" without any issue.
This code works in colab.
```
import tensorflow as tf
model = tf.keras.applications.nasnet.NASNetLarge(
      include_top=False,
      weights=None,
      input_tensor=None,
      input_shape=(416, 416, 3),
      pooling=None)
model.load_weights('/root/.keras/models/nasnet_large_no_top.h5')
```  
And as expected, the result is much better than train everything from scratch.
So even the structural is changed, it doesn't cause any problem right?

**Comment by taehoonlee** [comment]
@DableUTeeF, I figured out that the structural changes have disappeared since the `1.0.6` of keras-applications. Thus, now we can enable `NASNet(include_top=False)` with arbitrary input shapes. Finally you made the point clear :) Thank you

**Comment by hoangphucITJP** [comment]
I want to train EfficientNet on the grayscale images. But the 3 channels restriction makes me have to convert grayscale to RGB which is redundant.

Is there any way to train on 1-channel images?
