### ISSUE TITLE
I'm having same issue, i've install pip install -U git+https://github.com/keras-team/keras git+https://github.com/keras-team/keras-applications but found error.

### ISSUE THREAD

**Issue by DarkDetectiv** [keras-team/keras-applications#132]
I'm having same issue, i've install pip install -U git+https://github.com/keras-team/keras git+https://github.com/keras-team/keras-applications but found error.
here is the error

#Tempat Install package atau module

!pip install -U git+https://github.com/keras-team/keras git+https://github.com/keras-team/keras-application

Collecting git+https://github.com/keras-team/keras
  Cloning https://github.com/keras-team/keras to c:\users\lenovo\appdata\local\temp\pip-req-build-54p30x38

  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/keras-team/keras C:\Users\LENOVO\AppData\Local\Temp\pip-req-build-54p30x38
Cannot find command 'git' - do you have 'git' installed and in your PATH?

thanks for any helps :D

_Originally posted by @DarkDetectiv in https://github.com/keras-team/keras-applications/issues/100#issuecomment-522341468_

**Comment by taehoonlee** [comment]
@DarkDetectiv, It doesn't seem to be a Keras issue. The error message is `Cannot find command 'git' - do you have 'git' installed and in your PATH?`. You should install `git` first.

**Comment by DarkDetectiv** [comment]
@taehoonlee  thank you, i've install git, but still error when i try to instal !pip install -U git+https://github.com/keras-team/keras git+https://github.com/keras-team/keras-application

**Comment by taehoonlee** [comment]
@DarkDetectiv, Please share the error message.

**Comment by DarkDetectiv** [comment]
#Tempat Install package atau module

!pip install -U git+https://github.com/keras-team/keras git+https://github.com/keras-team/keras-application 

Collecting git+https://github.com/keras-team/keras
  Cloning https://github.com/keras-team/keras to c:\users\lenovo\appdata\local\temp\pip-req-build-anlz990q

  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/keras-team/keras C:\Users\LENOVO\AppData\Local\Temp\pip-req-build-anlz990q
Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by taehoonlee** [comment]
@DarkDetectiv, The error message is still `Cannot find command 'git' - do you have 'git' installed and in your PATH?`.

**Comment by DarkDetectiv** [comment]
@taehoonlee  yes sir

**Comment by taehoonlee** [comment]
@DarkDetectiv, I'll close the issue for now. Please feel free to open it again at any time if you have additional comments.
