### ISSUE TITLE
No module named 'resnet_152'

### ISSUE THREAD

**Issue by DarkDetectiv** [keras-team/keras-applications#133]
i run the code to clasification cars with dataset in picture, but i found error wit keras. i've installed keras and it say was satisfied. here is code that i search

import tarfile
import scipy.io
import numpy as np
import os
import cv2 as cv
import shutil
import random
from console_progressbar import ProgressBar
import keras
from resnet_152 import resnet152_model
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import CSVLogger, ModelCheckpoint, EarlyStopping
from keras.callbacks import ReduceLROnPlateau
import os

import matplotlib.pyplot as plt
import numpy as np
from keras.preprocessing import image
from sklearn.metrics import confusion_matrix
from tqdm import tqdm

from utils import load_model

import os
import time

import cv2 as cv
import keras.backend as K
import numpy as np
from console_progressbar import ProgressBar

from utils import load_model

import json
import os
import random

import cv2 as cv
import keras.backend as K
import numpy as np
import scipy.io

from utils import load_model

and here error
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-22-85108684969a> in <module>
      8 from console_progressbar import ProgressBar
      9 import keras
---> 10 from resnet_152 import resnet152_model
     11 from keras.preprocessing.image import ImageDataGenerator
     12 from keras.callbacks import CSVLogger, ModelCheckpoint, EarlyStopping

ModuleNotFoundError: No module named 'resnet_152'

**Comment by taehoonlee** [comment]
@DarkDetectiv, The latest releases may not include the latest models. If you want to use the bleeding edge version, you can try `pip install -U git+https://github.com/keras-team/keras git+https://github.com/keras-team/keras-applications`.

**Comment by DarkDetectiv** [comment]
@taehoonlee i've try but it can't to be install
here the error: 

(base) C:\Users\LENOVO>pip install -U git+https://github.com/keras-team/keras git+https://github.com/keras-team/keras-applications
Collecting git+https://github.com/keras-team/keras
  Cloning https://github.com/keras-team/keras to c:\users\lenovo\appdata\local\temp\pip-req-build-wbadiqq5
  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/keras-team/keras C:\Users\LENOVO\AppData\Local\Temp\pip-req-build-wbadiqq5
Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by taehoonlee** [comment]
@DarkDetectiv, It doesn't seem to be a Keras issue. The error message is `Cannot find command 'git' - do you have 'git' installed and in your PATH?`. You should install `git` first.

**Comment by taehoonlee** [comment]
@DarkDetectiv, I'll close the issue for now. Please feel free to open it again at any time if you have additional comments.
