### ISSUE TITLE
When to update MobileNetv3?

### ISSUE THREAD

**Issue by Stealers** [keras-team/keras-applications#135]
When to update MobileNetv3?

**Comment by taehoonlee** [comment]
@Stealers, I am also watching [the official release](https://github.com/tensorflow/models/issues/6815).

**Comment by ShukuiZhang** [comment]
+1

**Comment by skulhare** [comment]
https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet

**Comment by taehoonlee** [comment]
#176 has been merged. Thank you for being patient.
