### ISSUE TITLE
How to instantiate a Model with global variable models

### ISSUE THREAD

**Issue by gitfourteen** [keras-team/keras-applications#136]
In InceptionV3, can not figure out why [this line](https://github.com/keras-team/keras-applications/blob/master/keras_applications/inception_v3.py#L375) can create a model
`model = models.Model(inputs, x, name='inception_v3')`

and when trace back to this function **[get_submodules_from_kwargs(kwargs)](https://github.com/keras-team/keras-applications/blob/master/keras_applications/__init__.py#L13)**, it ends abruptly without further reference. Would  you please advise? thank you!

**Comment by taehoonlee** [comment]
@gitfourteen, The line you mentioned is one of the functional APIs. Please refer to [the documents](https://keras.io/getting-started/functional-api-guide/).

[The decorator](https://github.com/keras-team/keras/blob/master/keras/applications/inception_v3.py#L9) puts keras modules into `kwargs`, and then [the function](https://github.com/keras-team/keras-applications/blob/master/keras_applications/inception_v3.py#L135) gets keras modules from `kwargs`.

**Comment by gitfourteen** [comment]
@taehoonlee , thanks for your reply. I did not notice at first that the original import is under  tensorflow environment:
`from tensorflow.keras.applications.inception_v3 import InceptionV3`

But still I looked for `models.Model(...) ` in **keras-team/keras** in vain.

The reference chain for Model instantiation in tensorflow are like this:
`module.Module --> base_layer.Layer --> network.Network --> engine.training.Model --> models.py --> __init__.py --> @keras_modules_injection --> InceptionV3`
