### ISSUE TITLE
Keras decoder.predict won't work 

### ISSUE THREAD

**Issue by Elesa** [keras-team/keras-applications#137]
[VAE_test.txt](https://github.com/keras-team/keras-applications/files/3605088/VAE_test.txt)

Hello,

This is just to let you know that the keras VAE example (https://keras.io/examples/variational_autoencoder/)

produces error when you try to employ "decoder.predict" 
(if you run
x_encoded = encoder.predict(x_test)
x_decoded = decoder.predict(x_encoded)
)

Thanks,
Maria

**Comment by taehoonlee** [comment]
@Elesa, Please refer to [the decoding parts](https://github.com/keras-team/keras/blob/master/examples/variational_autoencoder.py#L73-L96). The correct usage is as follows:

```python
z_mean, _, _ = encoder.predict(x_test)
x_decoded = decoder.predict(z_mean)
```

**Comment by taehoonlee** [comment]
@Elesa, I'll close the issue for now. Please feel free to open it again at any time if you have additional comments.
