### ISSUE TITLE
a small mistake of resnet ,leading to inaccuracy shape of internal layer

### ISSUE THREAD

**Issue by ChienWong** [keras-team/keras-applications#161]
https://github.com/keras-team/keras-applications/blob/976050c468ff949bcbd9b9cf64fe1d5c81db3f3a/keras_applications/resnet50.py#L234
the MaxPooling need to add a extra argument "padding="same"", if not ,the output_shape of the layer is less 1 than normal

**Comment by jaketae** [comment]
I'd like to contribute to this. But before I jump in, can you clarify a bit more as to what the issue is? What do you mean by "normal" when you say "1 less than normal"?
