### ISSUE TITLE
Necessity of resnet50.py

### ISSUE THREAD

**Issue by jaketae** [keras-team/keras-applications#172]
### Summary

I'm wondering if it is necessary to keep resnet50.py given that resnet_common.py already encapsulates all variants of ResNet, including ResNet50. They seem to be independent implementations of the same model? Please let me know if I'm missing something. Thanks in advance.

### Environment
Leaving fields blank as the issue is irrelevant to build or runtime environment.
- Python version:
- Keras version:
- Keras-applications version:
- Keras backend with version:

**Comment by qlzh727** [comment]
@fchollet for this issue, I think keras.application is expect to export the symbol in resnet_common.py which is aligned with tf.keras.application.

**Comment by jaketae** [comment]
@qlzh727 Thanks for the input. Unfortunately, I’m not sure if I quite follow what you mean. Is resnet50.py still exported via TensorFlow? From what I see, TF nightly now has its own implementation of resnet independent of Keras.
