### ISSUE TITLE
AttributeError: Can't Import EfficientNet! 

### ISSUE THREAD

**Issue by innat** [keras-team/keras-applications#192]
### Environment
- Python version: Python 3.7.6
- Keras version: !pip install -U git+https://github.com/keras-team/keras
- Keras-applications version:
- Keras backend with version: Tensorflow-GPU 2.1.0

I tried following in kaggle

```python
import tensorflow as tf
tf.keras.applications.EfficientNetB0(
    include_top=True,
    weights="imagenet",
    input_tensor=None,
    input_shape=None,
    pooling=None,
    classes=1000,
    classifier_activation="softmax",
    **kwargs
)
```
And got the following:

`AttributeError: module 'tensorflow' has no attribute 'keras_applications'`

Which version is needed? In addition, why there are not built-in the application of `SeResNeXT` model in `keras`.

**Comment by darien-schettler** [comment]
Quote from [Tensorflow EfficientNet Documentation](https://www.tensorflow.org/api_docs/python/tf/keras/applications/efficientnet) 
- **`Note: This API is new and only available in tf-nightly.`**
