### ISSUE TITLE
VGG16

### ISSUE THREAD

**Issue by whatdhack** [keras-team/keras-applications#20]
Hi, I have been trying to figure out  how width and height  of an image is handled by  Keras applications.  For example if I  go through the VGG16 code in  https://keras.io/applications/  (copied below) , I see that  there is flipping of height and width.

```
from keras.applications.vgg16 import VGG16
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
import numpy as np

model = VGG16(weights='imagenet', include_top=False)

img_path = 'elephant.jpg'
img = image.load_img(img_path, )
x = image.img_to_array(img)
x1 = np.expand_dims(x, axis=0)
x2 = preprocess_input(x1)

features = model.predict(x2)
```

The image object uses PIL, and I see the following.

```
In [117]: img.size
Out[117]: (500, 375)

In [118]: x.shape
Out[118]: (375, 500, 3)

In [119]: x1.shape
Out[119]: (1, 375, 500, 3)

In [120]: x2.shape
Out[120]: (1, 375, 500, 3)
```

In the above img  shows 500 as width,  which is  the  how  the image supposed to be displayed.  However, after converting to numpy array,  width and height seems to be flipped.   What is the input_shape convention for VGG16  ? Which dimension is considered width  and height respectively ?  The example shape was for a square image 224x224x3, hence ambivalent.  Also, a related question  is how does that impact  usage ( as it is a pre-trained network).

**Comment by taehoonlee** [comment]
@whatdhack, It is just a convention of PIL rather than a flipping. You just forget the PIL format and handle a numpy array.

For ImageNet validation, the most widely used method of shaping is:
- resizing so that the short side is 256 (e.g., 375x500 -> 256x341) followed by
- cropping the center-middle 224x224 sub-region.

**Comment by whatdhack** [comment]
I  do not think  I understand the example you gave.  For example, can you elaborate how you got from 375x500 to  256x341  ?  

For the example code with "include_top=False", it matters which dimension of  input_shape corresponds to width and height.   For example if I want to  replace the whole image loading code in the example by my own code, I will need to know which dimension corresponds to width/height.

**Comment by whatdhack** [comment]
@taehoonlee ,  can you please complete the answer ? Otherwise I do not think this can be closed.

**Comment by taehoonlee** [comment]
@whatdhack,
- You can resize the example image with a scale of 0.68(=256/375), maintaining the aspect ratio.
- In the case of `include_top=False`, you can just feed a numpy array without any transformation.

**Comment by whatdhack** [comment]
@taehoonlee , thanks.  For the second part, are you saying width and height are interchangeable ?  How was the pre-trained VGG16 model trained - which tensor dimension was used as width during training  ?  I think  the network will not perform as well if the images are rotated by 90 degrees . The effect of mis-interpreting width for height will be similar.

**Comment by taehoonlee** [comment]
@whatdhack, The width and the height are NOT interchangeable. For most cases, people use a format of `NHWC` (sample x height x width x channel) or `NCHW` (sample x channel x height x width).

**Comment by taehoonlee** [comment]
@whatdhack, The `image_data_format` is orthogonal to models and it is already documented.  Please refer to [this](https://keras.io/applications/#vgg16). VGG supports both `NHWC` and `NCHW`. The example is the case of `NHWC`.

**Comment by whatdhack** [comment]
Really ?   All the Keras applications examples use preprocess_input . See for yourself  - https://keras.io/applications/#vgg16 .

**Comment by whatdhack** [comment]
@taehoonlee , looks like the convention is HW  ( versus WH) .     It certainly would not harm to add that to the input_shape  description -  in fact  would have saved this whole thread.

**Comment by taehoonlee** [comment]
@whatdhack, Where do you think it should be added?

**Comment by whatdhack** [comment]
@taehoonlee , ???   input_shape  of course !

**Comment by taehoonlee** [comment]
@whatdhack, Then, would you please make a pull request?
