### ISSUE TITLE
DenseNet variable size images

### ISSUE THREAD

**Issue by ialhashim** [keras-team/keras-applications#22]
Is their a fundamental problem with allowing input images of different size? I had to comment this line to allow training images of size 64x64. My goal is to experiment with progressive training where you train on smaller images then train on larger ones (idea advocated in the _fast.ai_ course).

https://github.com/keras-team/keras-applications/blob/235ca351c5de637061c96390186987412f2c7625/keras_applications/densenet.py#L186

Right now it complains about the image size, even though it seem it shouldn't once `include_top ` is `False`.

**Comment by taehoonlee** [comment]
@ialhashim, Most reference models for ImageNet (including DenseNet) perform 1/32 down-sampling followed by a global-pooling and a classification layer. Thus, the smallest possible `min_size` is 32; it is OK to create a DenseNet with `input_shape=(64, 64, 3)` if you change `min_size=64` in `_obtain_input_shape`.

The reason why `min_size` is set to 221, is a sort of convention. Usually, researchers handling ImageNet expect a 7x7 last feature map when a 224x224 input image is fed into a model. The 221 is the minimum value to make the last feature map as 7x7.

**Comment by ialhashim** [comment]
Wouldn't it be more flexible to have `min_size=32`? I had the wrong impression for a while that there is a strict requirement on the input image size. I feel its better to either set it to the minimum value possible, or include it as an argument in the constructor. Right now this default 221 value is ensuring that I have to modify `densenet.py` every time I train on a new machine / setup. 

We can already provide an input shape via `input_shape`, it is a bit frustrating that the model is not constructed even when providing `include_top=False` and the exact `input_shape` in the constructor.

**Comment by taehoonlee** [comment]
@ialhashim, I agree with `min_size=32` for models performing 1/32 down-sampling like DenseNet. I'll think about Inception-based models a little more and update soon. Thank you for the comment.

**Comment by taehoonlee** [comment]
@ialhashim, I have updated `min_size` as the minimum size to make the bottleneck size 1x1. Please check [the update](https://github.com/keras-team/keras-applications/commit/8ad32411a065d67262f76473b8508bb2ce3a2fa6) and the following table:

|                                       | Before | After |
|---------------------------------------|--------|-------|
| DenseNet121, DenseNet169, DenseNet201 | 221    | 32    |
| InceptionResnetV2, InceptionV3        | 139    | 75    |
| MobileNet, MobileNetV2                | 32     | -     |
| NASNetLarge, NASNetMobile             | 32     | -     |
| ResNet50                              | 197    | 32    |
| VGG16, VGG19                          | 48     | 32    |

**Comment by ialhashim** [comment]
Excellent, thanks!
