### ISSUE TITLE
version in setup.py, 1.0.2, is incorrect for the 1.0.4 tag

### ISSUE THREAD

**Issue by jjhelmus** [keras-team/keras-applications#32]
The [version recorded in the setup.py file for the 1.0.4 tag](https://github.com/keras-team/keras-applications/blob/1.0.4/setup.py#L24) is 1.0.2, which is incorrect.  The sdist on PyPI has the correct version in the setup.py file.  

This can causes issues if a checkout of the git tag is used as the mean to install keras-applications as the incorrect version will be recorded in the metadata.

I do not think anything should be done to fix this as changing a tag is a bad procedure.  I think it is useful to have this in the issue tracker in case anyone else runs into the issue.

**Comment by taehoonlee** [comment]
cc @fchollet
