### ISSUE TITLE
'get_submodules_from_kwargs' is not defined in resnet_common.py

### ISSUE THREAD

**Issue by yunkchen** [keras-team/keras-applications#35]
from . import get_submodules_from_kwargs

**Comment by phiyodr** [comment]
It is defined in `__init__.py`. See [keras-applications/keras_applications/\_\_init__.py](https://github.com/keras-team/keras-applications/blob/61de21815728aa66377ebb2a7b4c2f5492a34dd2/keras_applications/__init__.py)

**Comment by yunkchen** [comment]
It has been fixed now, https://github.com/keras-team/keras-applications/blob/add_resnet_variants/keras_applications/resnet_common.py#L30
