### ISSUE TITLE
DepthwiseConv2D and Separable Conv2D

### ISSUE THREAD

**Issue by omrylcn** [keras-team/keras-applications#37]
Hi, i got a question . I can not find solution.  What is the difference between DepthwiseConv2D and Separable Conv2D  ?

**Comment by taehoonlee** [comment]
@omrylcn, Please refer to [the keras codes](https://github.com/keras-team/keras/blob/master/tests/keras/backend/reference_operations.py#L70-L87).
- Depthwise: convolution with filter groups,
- Separable: convolution with (usually 1x1 size of) filter groups followed by normal convolution.

**Comment by omrylcn** [comment]
thanks your answer
