### ISSUE TITLE
Wrong order of layers for first Conv in densenet

### ISSUE THREAD

**Issue by kdkalvik** [keras-team/keras-applications#38]
I see that the first convolutional layer in [densenet ](https://github.com/keras-team/keras-applications/blob/9770691c9abad612de3595b972006df3c64d5727/keras_applications/densenet.py#L208) is followed by a BN and RELU layers but the original paper says all convolutional layers follow BN-RELU-CONV order. @taehoonlee's original [implementation ](https://github.com/taehoonlee/tensornets/blob/97ed2fc737608900559dee84dc5243d89a67cb50/tensornets/densenets.py#L23) also follows BN-RELU-CONV.

**Comment by taehoonlee** [comment]
@kdkalvik, I think that all the variants have the same configuration:
- the authors' the official repo (Torch): https://github.com/liuzhuang13/DenseNet/blob/master/models/densenet.lua#L102-L104
- TensorNets (TensorFlow): https://github.com/taehoonlee/tensornets/blob/97ed2fc737608900559dee84dc5243d89a67cb50/tensornets/densenets.py#L42
- Keras: https://github.com/keras-team/keras-applications/blob/master/keras_applications/densenet.py#L208-L211

Could you please elaborate the difference?

**Comment by kdkalvik** [comment]
I am sorry I guess I made a mistake. Only the [paper ](https://arxiv.org/pdf/1608.06993.pdf) suggests that all conv layers follow BN-RELU-CONV order. Although given that the author's implementation follows CONV-RELU-BN for the first conv, I guess they forgot to mention that.
