### ISSUE TITLE
`mixed2` dimension in Inception v3

### ISSUE THREAD

**Issue by xiaohk** [keras-team/keras-applications#39]
In file [inception_v3.py](https://github.com/keras-team/keras-applications/blob/9770691c9abad612de3595b972006df3c64d5727/keras_applications/inception_v3.py#L216), the dimension of layer `mixed2` is supposed to be 35 x 35 x 256.

```
    # mixed 2: 35 x 35 x 256
    branch1x1 = conv2d_bn(x, 64, 1, 1)

    branch5x5 = conv2d_bn(x, 48, 1, 1)
    branch5x5 = conv2d_bn(branch5x5, 64, 5, 5)

    branch3x3dbl = conv2d_bn(x, 64, 1, 1)
    branch3x3dbl = conv2d_bn(branch3x3dbl, 96, 3, 3)
    branch3x3dbl = conv2d_bn(branch3x3dbl, 96, 3, 3)

    branch_pool = layers.AveragePooling2D((3, 3),
                                          strides=(1, 1),
                                          padding='same')(x)
    branch_pool = conv2d_bn(branch_pool, 64, 1, 1)
    x = layers.concatenate(
        [branch1x1, branch5x5, branch3x3dbl, branch_pool],
        axis=channel_axis,
        name='mixed2')
```

However, when I load a pre-trained Inception v3 model, the dimension becomes `(?, ?, ?, 288)`.

```
from keras.applications.inception_v3 import InceptionV3
base_model = InceptionV3(weights='imagenet', include_top=True)
base_model.get_layer("mixed2").output

# <tf.Tensor 'mixed2/concat:0' shape=(?, ?, ?, 288) dtype=float32>
```

All other concatenation layers match the dimensions noted in [inception_v3.py](https://github.com/keras-team/keras-applications/blob/9770691c9abad612de3595b972006df3c64d5727/keras_applications/inception_v3.py) except `mixed2` and `mixed1`. I am not sure what I am missing here?

**Comment by taehoonlee** [comment]
@xiaohk, Please refer to [the update](https://github.com/keras-team/keras-applications/commit/5f12ac88d660906ee3711c359d11618b33e661e5). Now, you can see the exact shape as follows:
```python
from keras.applications.inception_v3 import InceptionV3
base_model = InceptionV3(weights='imagenet', include_top=True)
print(base_model.get_layer("mixed2").output_shape)
# (None, 35, 35, 288)
```

**Comment by xiaohk** [comment]
@taehoonlee Thanks for the reply and commit. Shouldn't the dimension for `mixed2` be `(35, 35, 256)` instead of `(35, 35, 288)`?

**Comment by taehoonlee** [comment]
@xiaohk, Sorry for missing that point. 288 (=64+64+96+64) is correct because the `mixed2` is a concatenation of `branch1x1 (64), branch5x5 (64), branch3x3dbl (96), branch_pool (64)`. You can also check Table 1 (6 page) in [the paper](https://arxiv.org/pdf/1512.00567.pdf).

**Comment by taehoonlee** [comment]
The comments have been also updated.

**Comment by taehoonlee** [comment]
@xiaohk, I'll close the issue for now. Please feel free to open it again at any time if you have additional comments.
