### ISSUE TITLE
Error 404 when importing InceptionV3

### ISSUE THREAD

**Issue by alexhagen** [keras-team/keras-applications#43]
Hello, I get
```
Exception: URL fetch failure on https://github.com/fchollet/deep-learning-models/releases/download/v0.5/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5: None -- [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
```
When trying to import InceptionV3 on Python3.6, using
```python
from keras.applications.inception_v3 import InceptionV3
basemodel = InceptionV3(weights='imagenet', include_top=False)
```

If you go to the link, it's a 404 error.

**Comment by alexhagen** [comment]
Same thing happens for VGG16.

**Comment by taehoonlee** [comment]
@alexhagen, your example works well in my PC. Can you try it on another PC? There seems to be a network problem.

**Comment by alexhagen** [comment]
I am able to go to [the model](https://github.com/fchollet/deep-learning-models/releases/download/v0.5/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5) using the URL printed in the error output.  Actually, that part was a silly mistake of mine: the error output prints the url with a ":" appended to the end, and when you click it as a link, it will take you to a 404.  So the file exists.

However, I still get the "URL fetch failure" error.  Looking a little further into the SSL certificates, it seems that Python 3.6 on OSX has no default installed certificates, and one must run `/Applications/Python\ 3.6/Install\ Certificates.command` (from [this issue](https://github.com/ageron/handson-ml/issues/46#issuecomment-311323613) ).  Would it be appropriate to catch the error, and add an OSX specific message suggesting that users run that script?  If so, I can fork and open a pull request with that error catching.

**Comment by taehoonlee** [comment]
That is a good point for OSX users, however, it seems to me the error is orthogonal to Keras. Thank you for the comments, @alexhagen! :)
