### ISSUE TITLE
ValueError: Input 0 is incompatible with layer global_average_pooling2d_1: expected ndim=4, found ndim=2

### ISSUE THREAD

**Issue by tejasri19** [keras-team/keras-applications#45]
I'm doing image classification using inceptionv3 model. When i try to import pretrained model weights i get error as below. Can anyone please help me fix it

```  File "train.py", line 118, in <module>
    x = GlobalAveragePooling2D()(x)
  File "/home/isemes/anaconda3/envs/tensorflow-venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 414, in __call__
    self.assert_input_compatibility(inputs)
  File "/home/isemes/anaconda3/envs/tensorflow-venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 311, in assert_input_compatibility
    str(K.ndim(x)))
ValueError: Input 0 is incompatible with layer global_average_pooling2d_1: expected ndim=4, found ndim=2
```

**Comment by taehoonlee** [comment]
@tejasri19, Please let me know the versions of keras and keras-applications. Maybe, in my guess, the problem will disappear if you install the latest versions. Please `pip install -U keras keras-applications`.

**Comment by tejasri19** [comment]
> @tejasri19, Please let me know the versions of keras and keras-applications. Maybe, in my guess, the problem will disappear if you install the latest versions. Please `pip install -U keras keras-applications`.

Yes , i resolved it by installing latest version. Thanks :)

**Comment by raghuram-kukun** [comment]
Hi @taehoonlee, I am encountering the same issue. I followed your suggestion to install the latest version of Keras.  I have already installed the latest version of Keras, yet the issue is unresolved. My version of Keras is 2.2.4 and Keras-applications is 1.0.8, and Tensorflow is 1.14.0.

**Comment by Stancoo** [comment]
Hi, I have exactly the same problem. Keras packages are the same as above. Only the Tensorflow is 1.13.1

**Comment by Stancoo** [comment]
... but. I just forgot to remove a top layer in the basic model (in my case it is VGG16):  

model = VGG16(include_top=False)

.. and then it worked.
