### ISSUE TITLE
Is there some way to override the model download entrypoint?

### ISSUE THREAD

**Issue by aisensiy** [keras-team/keras-applications#47]
https://github.com/keras-team/keras-applications/blob/13f75fa3640098b26db8eb732f39b891481795a5/keras_applications/resnet50.py#L24

The model download speed is not optimized if just download from github, is there some way to make the download from my own mirror entrypoint?

**Comment by taehoonlee** [comment]
Welp. There may be possible ways to optimize the download speed, but we are not experts on it. We would appreciate if you could investigate the ways, @aisensiy.

**Comment by taehoonlee** [comment]
@aisensiy, I'll close the issue for now. Please feel free to open it again at any time if you have additional comments.
