### ISSUE TITLE
Resnet50: Mismatched documentation and error on the minimum input width/height

### ISSUE THREAD

**Issue by plapa** [keras-team/keras-applications#49]
Hey,

I am trying to import the ResNet50 network on an image classification problem
The input shape I am feeding it is (64, 64, 3), and the [documentation](https://keras.io/applications/#resnet50) mentions that the minimum input width / height is (32, 32). 

This is the the code I am using to load the 
`model = ResNet50(include_top=False, input_shape=(64,64,3), classes=2, weights=None)`

This is the error code I am getting:
```
   model = ResNet50(include_top=False, input_shape=(64,64,3), classes=2, weights=None)
  File "/usr/local/lib/python3.5/dist-packages/keras_applications/resnet50.py", line 198, in ResNet50
    weights=weights)
  File "/usr/local/lib/python3.5/dist-packages/keras_applications/imagenet_utils.py", line 316, in _obtain_input_shape
    str(input_shape) + '`')
ValueError: Input size must be at least 197x197; got `input_shape=(64, 64, 3)`

```

In theory ( 64, 64), should be accepted. Is there any error in my code, is the documentation mismatched with the code? 
How can I solve this?

Thank you!!

**Comment by taehoonlee** [comment]
@plapa, Please let me know the versions of keras and keras-applications. Maybe, in my guess, the problem will disappear if you install the latest versions. Please `pip install -U keras keras-applications`.

**Comment by plapa** [comment]
This were my versions:

Keras==2.2.0
Keras-Applications==1.0.2
Keras-Preprocessing==1.0.1

When I updated it, using @taehoonlee instructions, it started working again. Thank you!
