### ISSUE TITLE
Will the weight paths be pointed to this repo's releases?

### ISSUE THREAD

**Issue by CMCDragonkai** [keras-team/keras-applications#52]
I can see that the source code still points to https://github.com/fchollet/deep-learning-models/releases. Will these end up pointing to: https://github.com/keras-team/keras-applications/releases? The deep-learning-models repo README says its now deprecated.

**Comment by taehoonlee** [comment]
Sorry for the late response, @CMCDragonkai. The deprecated one is just the deep-learning-models repo. The weights in "deep-learning-models/releases" will continue to be maintained.
