### ISSUE TITLE
In both MobileNet and MobileNet V2, get ValueError about shape.

### ISSUE THREAD

**Issue by Luckick** [keras-team/keras-applications#56]
ValueError: Error when checking target: expected out_relu to have 4 dimensions, but got array with shape (32, 7)
(I have 7 classes in my label.)

Anybody can help?

**Comment by taehoonlee** [comment]
@Luckick, Can you share your code snippets to reproduce the error?

**Comment by Luckick** [comment]
The code is:

```
model = mobilenet_v2.MobileNetV2(input_shape=(224, 224, 3), alpha=1.0, depth_multiplier=1,
                      include_top=False, weights='imagenet', input_tensor=None, pooling=None,
                                     classes=7, backend=keras.backend,
                                     layers = keras.layers, models = keras.models, utils = keras.utils)
opt = Adam()
model.compile(optimizer=opt, loss='categorical_crossentropy',
                  metrics=['accuracy'])  

testX = X[idx_fold[idx]:idx_fold[idx+1],:,:,:]
testY = Y[idx_fold[idx]:idx_fold[idx+1],:]
    
trainX = np.delete(X, range(idx_fold[idx],idx_fold[idx+1]), axis=0)
trainY = np.delete(Y, range(idx_fold[idx],idx_fold[idx+1]), axis=0)
train_datagen.fit(trainX)
test_datagen.fit(testX)
    
train_generator = train_datagen.flow(trainX, trainY, batch_size=batch_size)
validation_generator = test_datagen.flow(testX, testY, batch_size=batch_size)
prediction_generator = test_datagen.flow(testX, y=testY, batch_size=batch_size, shuffle=False)    
    
history = model.fit_generator( train_generator, 
                        validation_data=validation_generator, 
                        steps_per_epoch=len(trainX) // batch_size, epochs=epochs, 
                        validation_steps=len(testX) // batch_size,
                        callbacks = [reduce_lr])
```
Where train_datagen is `train_datagen = ImageDataGenerator(...)`
Thank you!

**Comment by Luckick** [comment]
> @Luckick
> 
> 1. You should import from `keras` NOT `keras-applications` (e.g., `from keras.applications.mobilenet_v2 import MobileNetV2`) and do not need to feed `backend/layers/models/utils`.
> 2. If using `weights='imagenet'` with `include_top=True`, `classes` should be 1000.
> 3. If you want to conduct transfer learning, [the official example "Fine-tune InceptionV3 on a new set of classes"](https://keras.io/applications/) would be helpful.

1. Yes I am using `from keras.applications.mobilenet_v2 import MobileNetV2`
   And I just delete `backend/layers/models/utils`
2. I set `include_top=False`

But the error still show up. Anywhere else should I take care of?
Thanks!
