### ISSUE TITLE
Error of Custom DenseNet layer blocks=[2,2,2,2]

### ISSUE THREAD

**Issue by qxde01** [keras-team/keras-applications#66]
```from keras.layers import *
x=Input(shape=(224,224,3))
from keras_applications import densenet
model=densenet.DenseNet(blocks=[2,2,2,2],weights=None,input_tensor=x)
```
or
```
from keras.applications import densenet
model=densenet.densenet.DenseNet(blocks=[2,2,2,2],weights=None,input_tensor=x)
```

> Error:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Py36\Python36\lib\site-packages\keras_applications\densenet.py", line 193, in DenseNet
    data_format=backend.image_data_format(),
AttributeError: 'NoneType' object has no attribute 'image_data_format'

**Comment by qxde01** [comment]
@taehoonlee thank you.
It can be solved as follows：
```
x=Input(shape=(224,224,3))
model=densenet.DenseNet(blocks=[2,2,2,2],weights=None,input_tensor=x,backend=keras.backend,layers=keras.layers,...)
```

**Comment by taehoonlee** [comment]
@qxde01, Yes, that is also possible. Thank you!
