### ISSUE TITLE
Dropout error with keras functional API

### ISSUE THREAD

**Issue by aakashbehl1994** [keras-team/keras-applications#67]
I can't use dropout on keras functional API, I get a resource exhaustion error. 

![dropout](https://user-images.githubusercontent.com/31963235/52145088-1e757c80-2686-11e9-9a48-44457063d26d.JPG)

Before using dropout my code was working fine but now I am getting this error

![dropout_error](https://user-images.githubusercontent.com/31963235/52145197-5d0b3700-2686-11e9-8095-ba97854b4a21.JPG)

![dropout_error2](https://user-images.githubusercontent.com/31963235/52145207-63011800-2686-11e9-9fbc-047d33af4676.JPG)

**Comment by taehoonlee** [comment]
@aakashbehl1994, Thank you for trying Keras. The OOM error is related to not Keras but your machine. The dropout layer requires additional memory for the masking matrix even if there is no weights in dropout.
