### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'image_data_format' when creating model

### ISSUE THREAD

**Issue by sun-yitao** [keras-team/keras-applications#69]
Steps to replicate: (tried on MacOS Mojave and Windows 10)
```
$conda install tensorflow-gpu keras 
The following packages will be UPDATED:

    keras:               2.2.2-0                   --> 2.2.4-0
    keras-applications:  1.0.4-py36_1              --> 1.0.6-py36_0
    keras-base:          2.2.2-py36_0              --> 2.2.4-py36_0
    keras-preprocessing: 1.0.2-py36_1              --> 1.0.5-py36_0
    tensorboard:         1.10.0-py36he025d50_0     --> 1.12.2-py36h33f27b4_0
    tensorflow:          1.10.0-gpu_py36h3514669_0 --> 1.12.0-gpu_py36ha5f9131_0
    tensorflow-base:     1.10.0-gpu_py36h6e53903_0 --> 1.12.0-gpu_py36h6e53903_0
    tensorflow-gpu:      1.10.0-hf154084_0         --> 1.12.0-h0d30ee6_0

Proceed ([y]/n)? y
```
```conda create -n testenv tensorflow-gpu keras``` works too
```
$python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 28 2018, 19:44:12) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using TensorFlow backend.
>>> from keras_applications.xception import Xception
>>> Xception()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\USER\AppData\Local\conda\conda\envs\yitao\lib\site-packages\keras_applications\xception.py", line 107, in Xception
    if backend.image_data_format() != 'channels_last':
AttributeError: 'NoneType' object has no attribute 'image_data_format'
```
Creating a ResNeXt (keras applications 1.0.7) and Inception v3 model also gives the same error. I also tried installing keras and keras-applications using pip but same error again. Downgrading to keras 2.2.2 and everything will work properly.

Update: I found that this works:
```
import keras
from keras import applications
model = applications.xception.Xception()
```
However I'm not sure if this is the intended usage as the docs seem to be using the previous style of ```from keras.applications.inception_v3 import InceptionV3```

**Comment by taehoonlee** [comment]
@sun-yitao, [The official documents](https://keras.io/applications/) say `from keras_applications.xception import Xception` not `from keras_applications.xception import Xception`.

**Comment by sun-yitao** [comment]
Oh dear must have seen wrongly, will close this issue now

**Comment by Kautenja** [comment]
alternatively, you can use the following to interact with keras_applications directly. I had to do so to get access to ResNet101 that is unavailable through keras.applications for some reason.

```python
import keras
import keras_applications
keras_applications.set_keras_submodules(
    backend=keras.backend,
    layers=keras.layers,
    models=keras.models,
    utils=keras.utils
)
```

**Comment by taehoonlee** [comment]
@Kautenja, That can be one of the workarounds. Thank you.

**Comment by kkanellis** [comment]
FYI this no longer works, as the `set_keras_submodules` functions has been removed from `__init__.py`

**Comment by SidGATOR** [comment]
You can set it using this:
`import keras`
`import keras_applications`
`application = {"backend" : keras.backend,"layers" : keras.layers,"models" : keras.models,"utils" : keras.utils}`
`keras_applications.get_submodules_from_kwargs(application)`

**Comment by idearibosome** [comment]
@kkanellis Instead of using ```set_keras_submodules```, you can directly pass the keras submodules when you create the model, e.g.,

```python
import keras
import keras_applications

resnet = keras_applications.resnet.ResNet101(
    backend=keras.backend,
    layers=keras.layers,
    models=keras.models,
    utils=keras.utils
)
```

**Comment by TahaAnwar** [comment]
> @kkanellis Instead of using `set_keras_submodules`, you can directly pass the keras submodules when you create the model, e.g.,
> 
> ```python
> import keras
> import keras_applications
> 
> resnet = keras_applications.resnet.ResNet101(
>     backend=keras.backend,
>     layers=keras.layers,
>     models=keras.models,
>     utils=keras.utils
> )
> ```

Model loads with this but later and .predict() This  gives this error:
'NoneType' object has no attribute 'image_data_format'

**Comment by astronstar** [comment]
from keras_applications import resnet_common
