### ISSUE TITLE
Resnet50 : ImportError: cannot import name '_obtain_input_shape'

### ISSUE THREAD

**Issue by andrewferlitsch** [keras-team/keras-applications#72]
I am getting an error on the import line below:

from keras.applications.imagenet_utils import _obtain_input_shape
ImportError: cannot import name '_obtain_input_shape'

I did the latest pip install of keras and keras-applications. Still get the error.

pip install -U keras keras-applications

**Comment by taehoonlee** [comment]
@andrewferlitsch, the `_obtain_input_shape` is designed for internal only.
