### ISSUE TITLE
 ResNeX

### ISSUE THREAD

**Issue by MinuteswithMetrics** [keras-team/keras-applications#79]
I tried to import ResNext50 into Kaggle kernels and received ModuleNotFoundError:

```
<ipython-input-7-4bb1f00ad376> in <module>()

     1 import keras

   ----> 2 from keras.applications.resnext import ResNeXt50

 ModuleNotFoundError: No module named 'keras.applications.resnext'
```

I so happen to find **keras-applications** while searching for Se_ResNext50 code and keras. Is this available for use now? Or, will this be available during the next Keras update.  Is it best to run `!git clone` command to get it to work in kaggle kernel? Thank you for assistance.

**Comment by taehoonlee** [comment]
@MinuteswithMetrics, the latest release (2.2.4) don't include the resnext models. If you want to use the bleeding edge version, you can try `pip install -U git+https://github.com/keras-team/keras git+https://github.com/keras-team/keras-applications`.

**Comment by MinuteswithMetrics** [comment]
@taehoonlee Thank you
