### ISSUE TITLE
Unable to run ResNeXt101, ResNet152V2

### ISSUE THREAD

**Issue by jalilnoormohammadi** [keras-team/keras-applications#83]
When I am running  ResNeXt101, ResNet152V2... I got the following error. 

AttributeError: 'NoneType' object has no attribute 'image_data_format'

Could you please tell me what is wrong with that?

**Comment by Ivan-wang** [comment]
a solution here: #79

**Comment by taehoonlee** [comment]
@jalilnoormohammadi, The keras-applications is not a standalone library. You must import with `from keras.applications.ooo import ooo` NOT `from keras_applications.ooo import ooo`.
