### ISSUE TITLE
Buffered data was truncated after reaching the output size limit.

### ISSUE THREAD

**Issue by sauronpy** [keras-team/keras-applications#89]
when training process is going forward, suddenly this error appears.

can anyone tell me what is the problem??

i have 12gig graphic memory (VRAM) and this problem is not related to graphic hardware.

this problem, one time appears in epoch 120 and another time appears in epoch 50, and one time do not appears at all.

`Epoch 141/400
17024/50000 [=========>....................] - ETA: 1:50 - loss: 0.1026 - acc: 0.9705 - top3_acc: 0.9991Buffered data was truncated after reaching the output size limit.`

**Comment by taehoonlee** [comment]
@sauronpy, The issue is not related to keras and keras-applications. Please refer to the https://stackoverflow.com/questions/51463383/buffered-data-was-truncated-after-reaching-the-output-size-limit.
