### ISSUE TITLE
Is a bug in NasNet ?

### ISSUE THREAD

**Issue by K0BigYang** [keras-team/keras-applications#95]
Hello,

Line 163 :     
    input_shape = _obtain_input_shape(input_shape,
                                      default_size=default_size,
                                      min_size=32,
                                      data_format=backend.image_data_format(),
                                      require_flatten=True,
                                      weights=weights)

I think that arguments is fine for that "require_flatten=include_top" .

**Comment by taehoonlee** [comment]
@K0BigYang, I hope the #62 will help you.

**Comment by K0BigYang** [comment]
Ok, thanks a lot.👍
